# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "D:/keith_temp/quartusII/DE2_System_v1.5/DE2_System_v1.5/DE2_demonstrations/DE2_NET/DE2_NET.qpf"
project_close