# TCL File Generated by Component Editor 11.1sp1
# Mon Jan 30 11:20:02 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | seg7_lut_8 "SEG7_LUT_8" v1.0.1
# | null 2012.01.30.11:20:02
# | 
# | 
# | D:/SVN/de2/test/Qsys_Q11_1/DE2_NET/ip/SEG7_LUT_8/hdl/SEG7_LUT_8.v
# | 
# |    ./hdl/SEG7_LUT.v syn, sim
# |    ./hdl/SEG7_LUT_8.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module seg7_lut_8
# | 
set_module_property NAME seg7_lut_8
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME SEG7_LUT_8
set_module_property TOP_LEVEL_HDL_FILE hdl/SEG7_LUT_8.v
set_module_property TOP_LEVEL_HDL_MODULE SEG7_LUT_8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME SEG7_LUT_8
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/SEG7_LUT.v {SYNTHESIS SIMULATION}
add_file hdl/SEG7_LUT_8.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk iCLK clk Input 1
add_interface_port clk iRST_N reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ENABLED true

add_interface_port avalon_slave_0_export oSEG0 export Output 7
add_interface_port avalon_slave_0_export oSEG1 export Output 7
add_interface_port avalon_slave_0_export oSEG2 export Output 7
add_interface_port avalon_slave_0_export oSEG3 export Output 7
add_interface_port avalon_slave_0_export oSEG4 export Output 7
add_interface_port avalon_slave_0_export oSEG5 export Output 7
add_interface_port avalon_slave_0_export oSEG6 export Output 7
add_interface_port avalon_slave_0_export oSEG7 export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 1
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDIG writedata Input 32
add_interface_port avalon_slave_0 iWR write Input 1
# | 
# +-----------------------------------
